spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/examLabDB
    username: myuser
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
