spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gcp:
      datastore:
        project-id: core-commerce-staging
        namespace: cart